### ISSUE TITLE
Error in Tracking

### ISSUE THREAD

**Issue by Hizafa-Nadeem** [ZexinChen/AlphaTracker#22]
I have encountered an error in tracking that a file has not found at the location: /gdrive/result_folder/oriFrameFromVideo//sample_video/frame_folder//*.txt. I am using the sample dataset and running the notebook on Colab. 

 What could be potential reason for the error. how can I resolve it?

![Screenshot 2022-09-26 154023](https://user-images.githubusercontent.com/73908345/192256960-da34b87d-364b-445d-b8d0-bf92c79fbfac.png)

**Comment by laurelrr** [comment]
Hello,

It appears that the program completed as expected and generated a tracked video for you here: /gdrive/result_folder/demo_2_0_060000.mp4.  
If you play that video, do you see the tracked results appearing as arrows on the video?

The last line is just trying to remove any text files generated during the processing.  It appears that none were created for you, which should be fine.  This is more of a warning than an error during processing.  If this warning bothers you, you can comment out the last line in the file 
Tracking/AlphaTracker/PoseFlow/tracker-general-fixNum-newSelect-noOrb.py:  Line 377

Thanks!

**Comment by Hizafa-Nadeem** [comment]
Got it. Thank you for your reply!
