### ISSUE TITLE
Error in clustering

### ISSUE THREAD

**Issue by Hizafa-Nadeem** [ZexinChen/AlphaTracker#23]
While running python fft_main_sep_twoMiceInteract.py . I received an error. Kindly, please inform what could be the potential reason for the error. I am using sample data and run the steps given on the Colab notebook.

![image](https://user-images.githubusercontent.com/73908345/192588151-349be62e-9d11-44f1-a8c3-ea364986e8f8.png)

After this step I run the Analysis notebook. I receive a file not found error. I have checked that there is no folder/directory named as results_social on my drive. Please inform what should be the location of the results?

![image](https://user-images.githubusercontent.com/73908345/192589068-9d056bdc-3b10-4b5e-8f00-0f3162f43edc.png)

**Comment by laurelrr** [comment]
Could you please check what is listed in AlphaTracker/BehavioralClustering/setting.py line 95:

The defaults should be:
        self.result_folder = './results/demo'

**Comment by laurelrr** [comment]
Also, the behavioral clustering has not been tested on Colaboratory.  You may need to manually run the commands in run_all.sh.

**Comment by Hizafa-Nadeem** [comment]
I changed this path to  self.result_folder = ./results/ind_clustering_demo.

**Comment by Hizafa-Nadeem** [comment]
I have also tried to run command in run_all.sh manually in Colab. However, the same error persists.
