### ISSUE TITLE
Install conda environment

### ISSUE THREAD

**Issue by xcccc402** [ZexinChen/AlphaTracker#4]
Hi:

 I have problem with the 'Install Conda environment'. May I have you generous help? Please see the attach for my command and the running results . 
<img width="633" alt="Screenshot 2020-12-14 at 16 49 20" src="https://user-images.githubusercontent.com/62570054/102059954-8a050500-3e2c-11eb-8930-af45cd26aab6.png">

**Comment by aneeshbal** [comment]
Hi, For this error, I would go to the environment.yml file, and comment out lines 4 and 5 by putting a "#" before the text. These dependencies have been changed recently and we are working on updating this, but for now, simply removing those two lines via comment will do.
